### ISSUE TITLE
scss files not compiled when in watch mode

### ISSUE THREAD

**Issue by vdest** [archfirst/angular2-seed-sass#13] opened 2016-04-15 08:07 UTC
When run in watch mode with `npm start`, any changes in scss files have no effect. The watcher detects the change, recompiles and reloads browser, but css changes are not applied. Changes to any other files (*.ts) are seen immediately after reload. 

However, when running `npm run build.prod` to make the production build, changes are properly compiled and seen.

**Comment by nareshbhatia** [comment] 2016-04-16 03:14
@vdest, I was able to reproduce this once but can't reproduce it any more. In my case, the browser was being reloaded, but the scss file was not being compiled. The dist directory had old compiled versions of css files which were not being overwritten. After I deleted the dist directly completely and re-ran `build start` everything started working correctly. Changing scss files is reloading the browser and showing changes correctly.

Can you please try completely cleaning the dist directory and trying this again?

**Comment by Geoide** [comment] 2016-04-16 11:05
For me, the problem appeared after the first `npm run build.prod`. I just deleted `tmp` directory inside `dist`. But I don't understand the real problem really.

**Comment by nareshbhatia** [comment] 2016-04-16 12:08
Thanks @Geoide - that was the clue. The real cause
of the problem was that `dist\tmp` is being shared between dev and prod
builds. This directory was not being cleaned up during a dev build. So
if there were files sitting in `dist\temp` from the prod build, then
dev build did not like it. Fixed by cleaning up tmp directory during
dev builds.

**Closed as completed by nareshbhatia** 2016-04-16 12:08 UTC

**Comment by vdest** [comment] 2016-04-16 13:38
Great! Works as expected now.
